services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-net

  producer:
    build:
      context: .
      dockerfile: services/producer/Dockerfile
    container_name: producer-service
    env_file:
      - .env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net

  consumer:
    build:
      context: .
      dockerfile: services/consumer/Dockerfile
    container_name: consumer-service
    env_file:
      - .env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net

  telegram-notifier:
    build:
      context: .
      dockerfile: services/telegram-notifier/Dockerfile
    container_name: telegram-notifier-service
    env_file:
      - .env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
